name: build


on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest

  build:
    name: Build and Test
    needs: golangci

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        goVersion: ["1.20", "1.21", "1.22"]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVersion }}
      
      - name: Test and coverage executions
        run: |
          mkdir -p bin
          go test ./...
