name: CI

on:
  push:
    branches:
      - "**"
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6
        with:
          version: latest

  test:
    name: Build and Test
    needs: golangci

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        goVersion: ["1.20", "1.21", "1.22"]

    steps:
      - name: Clone Repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: ${{ matrix.goVersion }}
      
      - name: Test and coverage executions
        run: |
          mkdir -p bin
          go test ./...
